### ISSUE TITLE
Behavior when xcfilelists are already up to date

### ISSUE THREAD

**Issue by Cronay** [artemnovichkov/Carting#62]
Hey,

I just wanted to ask if the behavior of carting is as expected. I updated every piece of software on our CI-Machine and carting had a change in behavior, to be precise when no dependency was added it now returns an error code in the command line when reporting "Nothing to update.". Because of this we had to change the way the dependencies are handled in the CI-Pipeline by checking in the xcfilelists which we until now hadn't checked in into version control. So we now have to run the command when adding a dependency on the developer's machine. This is absolutely no issue for us, was just a change that we didn't expect.

So to reiterate my question: Is it expected behavior that carting reports an error on the command line when there's nothing to update?

**Comment by gbreen12** [comment]
I think that it is expected but it shouldn't be. It doesn't make sense to me that having nothing to update would be an error.

**Comment by artemnovichkov** [comment]
Hi, @Cronay and @gbreen12! Sorry for the long time answer, I've missed notifications because of wrong watch settings for Carting. You're right, Carting throws the euro if there are nothing to update
https://github.com/artemnovichkov/Carting/blob/46ade32d87baa9909549af70ae273b55671671c3/Sources/CartingCore/Services/ProjectService.swift#L15
I agree that it should't be an error, maybe just a message in log. What do you think?

**Comment by Cronay** [comment]
Yes, I think the way it worked before the update should be restored and the program should return without an error when the xcfilelists are up to date.

**Comment by artemnovichkov** [comment]
Thank you for the feedback! I'll try to remove this error.

**Comment by artemnovichkov** [comment]
Added to [2.1.4](https://github.com/artemnovichkov/Carting/releases/tag/2.1.4) release. Thank you, guys!

**Comment by gbreen12** [comment]
Definitely better in my opinion! Thanks for the update
